services:
  shurl:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: [ "make", "migrate-up" ]
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
