FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache make

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go install github.com/githubnemo/CompileDaemon@latest

EXPOSE 8080

CMD ["make", "dev"]